language: python
python:
  - "3.6"
  - "3.7"
# there are some package problems with 3.8
#  - "3.8"
install:
  - pip install -r requirements.txt
script: bash test.sh
before_install:
  - "pip install -U pip"
  - "python setup.py install"